server {
    listen 80;
    server_name minecraftjapan.test;
    root /var/www/html;

    location / {
        index index.php index.html;
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        fastcgi_pass mediawiki:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
    }
}

    location ~* ^(.*\.(jpg|jpeg|gif|png|webp|pdf))$ {
        return 301 https://minecraftjapan.miraheze.org/wiki/Minecraft_Japan_Wiki/$1;
    }